### PR TITLE
add jump process with delay example

### PR DESCRIPTION
**Pull request by slwu89**
Hi @sdwfrost, this addresses (part of) #13 using callbacks and the DifferentialEquations.jl solver. Dynamics look much more like the DDE solutions than the Gillespie and jump process solutions, as expected.

### CODE REVIEW

**Comment by sdwfrost** [comment]
Thanks @slwu89! This is a nice and clear example of using the integrator interface directly.

**Comment by sdwfrost** [comment]
I added a fixed delay to [my DES example](https://github.com/epirecipes/sir-julia/blob/master/markdown/des/des.md) - there should be a check to ensure that the results are comparable.

**Comment by slwu89** [comment]
@sdwfrost could we compare the mean/some quantiles of a large number of simulations from both methods to the DDE solution? They should both be quite close I think.

**Comment by sdwfrost** [comment]
Yes, something simple like that should be sufficient. Comparing the empirical CDF of some quantity for the DES and your jump system should look like a straight line.

**Comment by slwu89** [comment]
OK I can do a comparison after I fix the problem of initial infectives not being queued for recovery in the jump example. Where should that notebook live?

**Comment by sdwfrost** [comment]
In some ways, I think the DES should be the gold standard, as it's the most general. In order to keep the notebooks separate, perhaps a distribution of the final size?

**Pull request merged**
